favicon: https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f435.svg
avatar: https://mstdn.ivtune.net/system/accounts/avatars/110/661/320/950/107/930/original/d63c1178c950220f.png
katex: false
force_https: true
check_update: false

menus:
  - name: Home
    link: /
  - name: Archives
    link: /archives/
  - name: Tags
    link: /tags/
post:
  feature: true
disqus:
  enable: false
  shortname: 'Your shortname here'
  api: 'Your api here'
  apikey: 'Your api key here'
  admin: 'Your disqus username here'
gitalk:
  enable: false
  clientId: 'Your Client Id here'
  clientSecret: 'Your Client Secret here'
  repository: 'Your Comment Repository here'
  owner: 'Your github username here'
valine:
  enable: false
  appId: 'Your appID here'
  appKey: 'Your appKey here'
  placeholder: 'Your placeholder here'
  pageSize: 10
web_analytics:
  enable: false
  google: UA-12345678-1
  baidu: 12345678
footer: |
  Footer HTML
friends:
  - name: 宝硕博客
    link: https://blog.baoshuo.ren/
    logo: https://cdn.jsdelivr.net/npm/bsi@0.0.2/favicon/128x128.png
    description: 学习，就是发现自己越来越菜的过程。
